export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const RETRIEVE_POST_SUCCESS = 'RETRIEVE_POST_SUCCESS';
export const RETRIEVE_POST_FAIL = 'RETRIEVE_POST_FAIL';
